### ISSUE TITLE
PyPi package

### ISSUE THREAD

**Issue by cirosantilli** [cirosantilli/vcdvcd#1]
This has been proposed.

I've never done it before, do I need to make any changes in the code to be able to upload to PyPi? If so, please send a pull request with the changes, and then I'll upload.

Otherwise, I'll upload soon.

**Comment by bmpenuelas** [comment]
Hi, I just submitted PR #2 with the required modifications.

[Here](https://blog.garageinsidegarage.com/python-stuff-to-remember-a-collection-of-snippets-and-modules-to-accelerate-your-development/#uploading-to-pypi-enable-anyone-to-pip-install-yourpackage) is a short guide to packaging a module and uploading it to PyPi.

With this PR everything is ready and the test upload was successful, you just need to:
`pip install setuptools setuptools wheel twine`
`python setup.py sdist bdist_wheel` (run in the same dir as setup.py)
`twine upload dist/*` (and provide your [PyPi](https://pypi.org/) credentials)

Please let me know if you need anything else.
