### ISSUE TITLE
TypeError: '<' not supported between instances of 'int' and 'str'

### ISSUE THREAD

**Issue by christian-krieg** [cirosantilli/vcdvcd#12]
It seems that the Signal class introduced in v2.0.0 breaks vcdvcd in line 272.

Whenever I parse a VCD file I get the following error:
```
TypeError: '<' not supported between instances of 'int' and 'str'
```

**Comment by cirosantilli** [comment]
Hi Christian, can you check that this is not the same as: https://github.com/cirosantilli/vcdvcd/issues/11

If not, provide a minimal example if possible.

**Comment by christian-krieg** [comment]
Hi Ciro,

Thanks a lot for pointing that out! It seems to be the same issue which has it's root cause in my code not using the new API correctly. For the moment, I will stick with v1.0.6, and adapt my code once I have time for it :)

Cheers,
Christian

**Comment by cirosantilli** [comment]
OK! I'll close for now, feel free to reopen if you find out it is a different thing later on.
